version: "3"
services:

  # Database
  wso2am-mysql-db-service:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wso2carbon
      MYSQL_PASSWORD: wso2carbon
    volumes:
      - ./configs/mysql/initdb:/docker-entrypoint-initdb.d
      - ./configs/mysql/my.cnf:/etc/mysql/my.cnf
      # This will persist the database data in a volume on the host
      # - mysql-datavolume:/var/lib/mysql 

  # Local Mailserver
  mailserver:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

  # API Manager
  apim:
    image: docker.wso2.com/wso2am:4.0.0.0 #4.0.0.0 is the latest 4.0 version alias
    user: "root"
    ports:
      - "9443:9443"
      - "8280:8280"
      - "8243:8243"
    entrypoint:
      - "sh"
      - "-c"
      - |
          wget -qO- https://raw.githubusercontent.com/eficode/wait-for/v2.1.0/wait-for | 
          sh -s -- wso2am-mysql-db-service:3306 --timeout=160 -- echo "db ready";

          # Pre-start commands:

          echo "starting APIM";
          $${WORKING_DIRECTORY}/docker-entrypoint.sh;
    volumes:
      - ./configs/apim:/home/wso2carbon/wso2-config-volume/repository/conf/
      - ./configs/security:/home/wso2carbon/wso2-config-volume/repository/resources/security
      - ./components/dropins:/home/wso2carbon/wso2-artifact-volume/repository/components/dropins/
      - ./components/plugins:/home/wso2carbon/wso2-artifact-volume/repository/components/plugins/
      - ./components/misc:/home/wso2carbon/wso2-artifact-volume/misc
    depends_on:
      - wso2am-mysql-db-service
      - mailserver

volumes:
  # Persistant mysql data
  mysql-datavolume:
    driver: local

networks:
  default:
    external: true
    name: apim-guides
