DROP DATABASE IF EXISTS WSO2AM_DB;
CREATE DATABASE WSO2AM_DB;
GRANT ALL ON WSO2AM_DB.* TO 'wso2carbon'@'%' IDENTIFIED BY 'wso2carbon';

DROP DATABASE IF EXISTS WSO2AM_SHARED_DB;
CREATE DATABASE WSO2AM_SHARED_DB;
GRANT ALL ON WSO2AM_SHARED_DB.* TO 'wso2carbon'@'%' IDENTIFIED BY 'wso2carbon';
